listen:
  host: "0.0.0.0"
  port: 8000
upstreams:
  - host: "127.0.0.1"
    port: 9001
  - host: "127.0.0.1"
    port: 9002
timeouts:
  connect_ms: 1000
  read_ms: 15000
  write_ms: 15000
  total_ms: 30000
limits:
  max_client_conns: 1000
  max_conns_per_upstream: 100
rate_limits:
  rate: 100
  capacity: 1000
  per_upstream: False
health_check:
  interval: 100
  timeout: 5
logging:
  level: "info"
