listen:
  - host: "0.0.0.0"
    port: 8000
upstreams:
  - host: "host.docker.internal"
    port: 9001
  - host: "host.docker.internal"
    port: 9002
timeouts:
  connect_ms: 1000
  read_ms: 15000
  write_ms: 15000
  total_ms: 30000
limits:
  max_client_conns: 10000
  max_conns_per_upstream: 1000
rate_limits:
  rate: 1000
  capacity: 10000
  per_upstream: False
health_check:
  interval: 10000
  timeout: 5
logging:
  level: "info"
